const data = [
 {
   "country": "NIGERIA",
   "country code": "NG",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 653.9883407128899,
   "unit": "KT",
   "Ranking": 1,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "NIGERIA",
   "country code": "NG",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 1491.0934168253889,
   "unit": "KT",
   "Ranking": 1,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "SUDAN",
   "country code": "SD",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 289.30850576256836,
   "unit": "KT",
   "Ranking": 2,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "SUDAN",
   "country code": "SD",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 659.6233931386557,
   "unit": "KT",
   "Ranking": 2,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "TANZANIA",
   "country code": "TZ",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 259.5635425,
   "unit": "KT",
   "Ranking": 3,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "TANZANIA",
   "country code": "TZ",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 591.8048769,
   "unit": "KT",
   "Ranking": 3,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "NIGER",
   "country code": "NE",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 187.613664,
   "unit": "KT",
   "Ranking": 4,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "NIGER",
   "country code": "NE",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 427.75915392,
   "unit": "KT",
   "Ranking": 6,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "COTE D'IVOIRE",
   "country code": "CI",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 211.79405999999997,
   "unit": "KT",
   "Ranking": 5,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "COTE D'IVOIRE",
   "country code": "CI",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 482.8904567999999,
   "unit": "KT",
   "Ranking": 5,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "ANGOLA",
   "country code": "AO",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 89.39663750000001,
   "unit": "KT",
   "Ranking": 6,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "ANGOLA",
   "country code": "AO",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 203.8243335,
   "unit": "KT",
   "Ranking": 8,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "ETHIOPIA",
   "country code": "ET",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 358.8711554712597,
   "unit": "KT",
   "Ranking": 7,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "ETHIOPIA",
   "country code": "ET",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 818.2262344744721,
   "unit": "KT",
   "Ranking": 4,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "CAMEROON",
   "country code": "CM",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 73.638075,
   "unit": "KT",
   "Ranking": 8,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "CAMEROON",
   "country code": "CM",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 167.894811,
   "unit": "KT",
   "Ranking": 14,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "BURKINA FASO",
   "country code": "BF",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 81.661818,
   "unit": "KT",
   "Ranking": 9,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "BURKINA FASO",
   "country code": "BF",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 186.18894504,
   "unit": "KT",
   "Ranking": 13,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "GUINEA",
   "country code": "GN",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 62.907495,
   "unit": "KT",
   "Ranking": 10,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "GUINEA",
   "country code": "GN",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 143.42908859999997,
   "unit": "KT",
   "Ranking": 17,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "UGANDA",
   "country code": "UG",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 75.21933,
   "unit": "KT",
   "Ranking": 11,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "UGANDA",
   "country code": "UG",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 171.50007240000002,
   "unit": "KT",
   "Ranking": 15,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "MOZAMBIQUE",
   "country code": "MZ",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 75.63289649999999,
   "unit": "KT",
   "Ranking": 12,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "MOZAMBIQUE",
   "country code": "MZ",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 172.44300402,
   "unit": "KT",
   "Ranking": 16,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "SENEGAL",
   "country code": "SN",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 58.64846774775728,
   "unit": "KT",
   "Ranking": 13,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "SENEGAL",
   "country code": "SN",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 133.71850646488662,
   "unit": "KT",
   "Ranking": 19,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "CHAD",
   "country code": "TD",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 54.6,
   "unit": "KT",
   "Ranking": 14,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "CHAD",
   "country code": "TD",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 124.48799999999999,
   "unit": "KT",
   "Ranking": 21,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "ZIMBABWE",
   "country code": "ZW",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 58.209617150837275,
   "unit": "KT",
   "Ranking": 15,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "ZIMBABWE",
   "country code": "ZW",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 132.717927103909,
   "unit": "KT",
   "Ranking": 20,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "GHANA",
   "country code": "GH",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 94.63964399999999,
   "unit": "KT",
   "Ranking": 16,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "GHANA",
   "country code": "GH",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 215.77838832,
   "unit": "KT",
   "Ranking": 11,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "TUNISIA",
   "country code": "TN",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 102.9811565,
   "unit": "KT",
   "Ranking": 17,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "TUNISIA",
   "country code": "TN",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 234.79703682,
   "unit": "KT",
   "Ranking": 10,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "ALGERIA",
   "country code": "DZ",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 121.1625862081621,
   "unit": "KT",
   "Ranking": 18,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "ALGERIA",
   "country code": "DZ",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 276.2506965546096,
   "unit": "KT",
   "Ranking": 9,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "MADAGASCAR",
   "country code": "MG",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 34.6402245,
   "unit": "KT",
   "Ranking": 19,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "MADAGASCAR",
   "country code": "MG",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 78.97971186,
   "unit": "KT",
   "Ranking": 24,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "LIBYA",
   "country code": "LY",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 37.24913353720693,
   "unit": "KT",
   "Ranking": 20,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "LIBYA",
   "country code": "LY",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 84.92802446483181,
   "unit": "KT",
   "Ranking": 25,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "CENTRAL AFRICAN REPUBLIC",
   "country code": "CF",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 18.9,
   "unit": "KT",
   "Ranking": 21,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "CENTRAL AFRICAN REPUBLIC",
   "country code": "CF",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 43.092,
   "unit": "KT",
   "Ranking": 27,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "MALAWI",
   "country code": "MW",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 39.430794500000005,
   "unit": "KT",
   "Ranking": 22,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "MALAWI",
   "country code": "MW",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 89.90221146,
   "unit": "KT",
   "Ranking": 26,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "BENIN",
   "country code": "BJ",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 55.22458365000001,
   "unit": "KT",
   "Ranking": 23,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "BENIN",
   "country code": "BJ",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 125.91205072200003,
   "unit": "KT",
   "Ranking": 23,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "SIERRA LEONE",
   "country code": "SL",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 16.632,
   "unit": "KT",
   "Ranking": 24,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "SIERRA LEONE",
   "country code": "SL",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 37.920959999999994,
   "unit": "KT",
   "Ranking": 29,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "BURUNDI",
   "country code": "BI",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 22.716046499999997,
   "unit": "KT",
   "Ranking": 25,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "BURUNDI",
   "country code": "BI",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 51.792586019999995,
   "unit": "KT",
   "Ranking": 28,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "MALI",
   "country code": "ML",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 83.00706749999999,
   "unit": "KT",
   "Ranking": 26,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "MALI",
   "country code": "ML",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 189.2561139,
   "unit": "KT",
   "Ranking": 22,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "SOMALIA",
   "country code": "SO",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 11.549999999999999,
   "unit": "KT",
   "Ranking": 27,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "SOMALIA",
   "country code": "SO",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 26.334,
   "unit": "KT",
   "Ranking": 33,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "NAMIBIA",
   "country code": "NA",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 8.4,
   "unit": "KT",
   "Ranking": 28,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "NAMIBIA",
   "country code": "NA",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 19.152,
   "unit": "KT",
   "Ranking": 34,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "ERITREA",
   "country code": "ER",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 7.245,
   "unit": "KT",
   "Ranking": 29,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "ERITREA",
   "country code": "ER",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 16.5186,
   "unit": "KT",
   "Ranking": 35,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "LIBERIA",
   "country code": "LR",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 6.696091499999999,
   "unit": "KT",
   "Ranking": 30,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "LIBERIA",
   "country code": "LR",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 15.267088619999997,
   "unit": "KT",
   "Ranking": 36,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "GUINEA-BISSAU",
   "country code": "GW",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 6.1047315,
   "unit": "KT",
   "Ranking": 31,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "GUINEA-BISSAU",
   "country code": "GW",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 13.918787819999997,
   "unit": "KT",
   "Ranking": 37,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "RWANDA",
   "country code": "RW",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 23.479658999999998,
   "unit": "KT",
   "Ranking": 32,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "RWANDA",
   "country code": "RW",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 53.533622519999994,
   "unit": "KT",
   "Ranking": 30,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "BOTSWANA",
   "country code": "BW",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 2.73,
   "unit": "KT",
   "Ranking": 33,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "BOTSWANA",
   "country code": "BW",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 6.2244,
   "unit": "KT",
   "Ranking": 39,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "ESWATINI",
   "country code": "SZ",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 1.8375,
   "unit": "KT",
   "Ranking": 34,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "ESWATINI",
   "country code": "SZ",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 4.1895,
   "unit": "KT",
   "Ranking": 41,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "LESOTHO",
   "country code": "LS",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 1.449,
   "unit": "KT",
   "Ranking": 35,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "LESOTHO",
   "country code": "LS",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 3.3037199999999998,
   "unit": "KT",
   "Ranking": 42,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "MAURITANIA",
   "country code": "MR",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 4.566387,
   "unit": "KT",
   "Ranking": 36,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "MAURITANIA",
   "country code": "MR",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 10.411362359999998,
   "unit": "KT",
   "Ranking": 38,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "EQUATORIAL GUINEA",
   "country code": "GQ",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 1.26,
   "unit": "KT",
   "Ranking": 37,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "EQUATORIAL GUINEA",
   "country code": "GQ",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 2.8728,
   "unit": "KT",
   "Ranking": 43,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "GABON",
   "country code": "GA",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 3.4125,
   "unit": "KT",
   "Ranking": 38,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "GABON",
   "country code": "GA",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 7.780499999999999,
   "unit": "KT",
   "Ranking": 40,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "CABO VERDE",
   "country code": "CV",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": null,
   "unit": "KT",
   "Ranking": 39,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "CABO VERDE",
   "country code": "CV",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": null,
   "unit": "KT",
   "Ranking": 44,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "COMOROS",
   "country code": "KM",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": null,
   "unit": "KT",
   "Ranking": 39,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "COMOROS",
   "country code": "KM",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": null,
   "unit": "KT",
   "Ranking": 44,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "CONGO (KINSHASA)",
   "country code": "CD",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": null,
   "unit": "KT",
   "Ranking": 39,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "CONGO (KINSHASA)",
   "country code": "CD",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": null,
   "unit": "KT",
   "Ranking": 44,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "CONGO (BRAZZAVILLE)",
   "country code": "CG",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": null,
   "unit": "KT",
   "Ranking": 39,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "CONGO (BRAZZAVILLE)",
   "country code": "CG",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": null,
   "unit": "KT",
   "Ranking": 44,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "ETHIOPIA",
   "country code": "ET",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": null,
   "unit": "KT",
   "Ranking": 39,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "ETHIOPIA",
   "country code": "ET",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": null,
   "unit": "KT",
   "Ranking": 44,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "GAMBIA",
   "country code": "GM",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": null,
   "unit": "KT",
   "Ranking": 39,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "GAMBIA",
   "country code": "GM",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": null,
   "unit": "KT",
   "Ranking": 44,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "SAO TOME AND PRINCIPE",
   "country code": "ST",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": null,
   "unit": "KT",
   "Ranking": 39,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "SAO TOME AND PRINCIPE",
   "country code": "ST",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": null,
   "unit": "KT",
   "Ranking": 44,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "SEYCHELLES",
   "country code": "SC",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": null,
   "unit": "KT",
   "Ranking": 39,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "SEYCHELLES",
   "country code": "SC",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": null,
   "unit": "KT",
   "Ranking": 44,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "SOUTH SUDAN",
   "country code": "SS",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": null,
   "unit": "KT",
   "Ranking": 39,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "SOUTH SUDAN",
   "country code": "SS",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": null,
   "unit": "KT",
   "Ranking": 44,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "MAURITIUS",
   "country code": "MU",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 0.2625,
   "unit": "KT",
   "Ranking": 48,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "MAURITIUS",
   "country code": "MU",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 0.5985000000000001,
   "unit": "KT",
   "Ranking": 53,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "KENYA",
   "country code": "KE",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 133.44145856575145,
   "unit": "KT",
   "Ranking": 49,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "KENYA",
   "country code": "KE",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 304.24652552991324,
   "unit": "KT",
   "Ranking": 12,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "TOGO",
   "country code": "TG",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 27.825,
   "unit": "KT",
   "Ranking": 50,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "TOGO",
   "country code": "TG",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 63.441,
   "unit": "KT",
   "Ranking": 32,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "MOROCCO",
   "country code": "MA",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 110.71217600000001,
   "unit": "KT",
   "Ranking": 51,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "MOROCCO",
   "country code": "MA",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 252.42376128000004,
   "unit": "KT",
   "Ranking": 18,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "ZAMBIA",
   "country code": "ZM",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 40.40807231693094,
   "unit": "KT",
   "Ranking": 52,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "ZAMBIA",
   "country code": "ZM",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 92.13040488260253,
   "unit": "KT",
   "Ranking": 31,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "SOUTH AFRICA",
   "country code": "ZA",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 194.62146049106778,
   "unit": "KT",
   "Ranking": 53,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "SOUTH AFRICA",
   "country code": "ZA",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 443.7369299196345,
   "unit": "KT",
   "Ranking": 7,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "EGYPT",
   "country code": "EG",
   "target type": "Abuja Target : 50Kg/Ha",
   "value": 47.393280000000004,
   "unit": "KT",
   "Ranking": 54,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 },
 {
   "country": "EGYPT",
   "country code": "EG",
   "target type": "Agronomy Target : 114Kg/Ha",
   "value": 108.05667840000001,
   "unit": "KT",
   "Ranking": 54,
   "indicator": "Potential Phosphorus Consumption (P2O5)",
   "year": 2020,
   "source": "Internal",
   "api_url": "Internal",
   "extracted_on": "2023-10-23"
 }
]
//make object of just countries 

let s = new Set()
for(i of data)
s.add(i["country"])
s = [...s]
s = s.map((i) => {
    return {country: i}
})
console.log(s)